### ISSUE TITLE
Research also increases enemy damage

### ISSUE THREAD

**Issue by Flame1869** [TheSAguy/Natural_Evolution_Enemies#1]
It seems some research also increases the attacks of the biters, probably because they are using the same weapons as some of the player base.
Possibly this is due to the combination of mods in my game (Natural evolution enemies / Bob's enemies / Armored Biters.

This is possibly unintended behavior.
it is yet unclear if it actually increases biter damage, or if its only a visual bug. i am uncertain how to test this.

Screenshot attached
![biter](https://github.com/TheSAguy/Natural_Evolution_Enemies/assets/75633209/daa4c46d-91cd-44a1-bd72-f2ac73921284)

**Comment by TheSAguy** [comment]
Thanks for the report, Should now be fixed in 1.1.15

**Comment by Flame1869** [comment]
Tested; solved! thanx a lot!
